services:
  frontend:
    build: 
      context: ./front
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./back
    ports:
      - "8000:8000"
    environment:  
      - NODE_ENV=development
      
